import React, { useState } from 'react';
import { ShieldCheck, CheckCircle2, XCircle, ChevronDown, Terminal, HelpCircle } from 'lucide-react';

export const WhyDaniyalSection: React.FC = () => {
  const comparisonRows = [
    {
      dimension: 'Keyword Strategy',
      traditional: 'Broad keyword stuffing & chasing vanity volume with zero commercial relevance.',
      daniyal: 'Commercial intent clustering, semantic topic silos, and entity mapping.'
    },
    {
      dimension: 'Technical Diagnosis',
      traditional: 'Automated 100-page generic PDF dumps generated by software tools.',
      daniyal: 'Code-level audit of crawl budget, server log files, canonical integrity & Core Web Vitals.'
    },
    {
      dimension: 'Content Architecture',
      traditional: 'Spinning 30 shallow blog posts per month on disconnected topics.',
      daniyal: 'Parent-child document hierarchies, JSON-LD schema graphs, and comprehensive topical authority.'
    },
    {
      dimension: 'Internal Link Graph',
      traditional: 'Random generic anchor text like "click here" leaving high-value commercial pages orphaned.',
      daniyal: 'Engineered link equity flow ensuring commercial landing pages sit at depth ≤ 3 clicks.'
    },
    {
      dimension: 'Local SEO Karachi',
      traditional: 'Superficial directory spam with mismatched NAP data.',
      daniyal: 'Targeted district Map Pack dominance (DHA, Clifton, Gulshan) & localized geo-schema.'
    },
    {
      dimension: 'Measurement & Reporting',
      traditional: 'Vanity impression reports and cherry-picked non-competitive keyword rankings.',
      daniyal: 'Transparent Google Search Console query logs, indexing velocity & assisted lead conversions.'
    },
    {
      dimension: 'Execution & Delivery',
      traditional: 'Account manager middlemen passing your tasks to inexperienced offshore interns.',
      daniyal: 'Direct collaboration with the technical SEO specialist executing the architectural changes.'
    }
  ];

  return (
    <section id="why-daniyal" className="py-24 sm:py-32 bg-[#060909] relative border-t border-white/5">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="max-w-3xl mb-16 text-left">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-xs font-semibold text-[#00E59B] uppercase mb-4">
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>THE ARCHITECTURAL DIFFERENCE</span>
          </div>

          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-[800] text-[#F4FAF7] tracking-[-0.035em] leading-[1.04] antialiased">
            Why Daniyal Asad vs.{' '}
            <span className="text-gradient-emerald">Traditional SEO Agencies.</span>
          </h2>

          <p className="mt-4 text-base sm:text-lg text-[#94A3B8] leading-relaxed">
            Most SEO retainers fail because they prioritize superficial checklists over root-cause architecture. Here is how my search engineering methodology compares to the traditional agency model.
          </p>
        </div>

        {/* Comparison Table / Matrix */}
        <div className="rounded-3xl bg-[#080D0D]/95 border border-emerald-500/20 overflow-hidden shadow-[0_25px_60px_rgba(0,0,0,0.8)]">
          {/* Table Header */}
          <div className="grid grid-cols-12 p-4 sm:p-6 bg-[#0D1414] border-b border-white/8 text-xs font-semibold">
            <div className="col-span-3 sm:col-span-3 text-[#5E736D] uppercase">
              Strategic Dimension
            </div>
            <div className="col-span-4 sm:col-span-4 text-[#94A3B8] uppercase flex items-center space-x-1.5">
              <XCircle className="w-3.5 h-3.5 text-red-400/80" />
              <span className="truncate">Traditional Agency Model</span>
            </div>
            <div className="col-span-5 sm:col-span-5 text-[#00E59B] uppercase flex items-center space-x-1.5">
              <CheckCircle2 className="w-3.5 h-3.5 text-[#00E59B]" />
              <span className="truncate">Daniyal Asad Search Architecture</span>
            </div>
          </div>

          {/* Table Rows */}
          <div className="divide-y divide-white/5 text-xs">
            {comparisonRows.map((row, idx) => (
              <div
                key={row.dimension}
                className="grid grid-cols-12 p-4 sm:p-6 hover:bg-white/[0.02] transition-colors items-center"
              >
                <div className="col-span-3 sm:col-span-3 font-semibold text-white pr-2">
                  {row.dimension}
                </div>
                <div className="col-span-4 sm:col-span-4 text-[#94A3B8] pr-4 text-[11px] sm:text-xs leading-relaxed font-normal">
                  {row.traditional}
                </div>
                <div className="col-span-5 sm:col-span-5 text-[#F4FAF7] text-[11px] sm:text-xs leading-relaxed font-medium pl-1 bg-emerald-500/[0.03] py-1 rounded">
                  <span className="text-[#00E59B] mr-1">✓</span>
                  {row.daniyal}
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </section>
  );
};

/* Section 15: FAQ Minimalist Accordion */
export const FaqSection: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      q: 'What makes technical SEO different from standard on-page SEO?',
      a: 'Standard on-page SEO typically focuses on inserting keywords into title tags and writing body copy. Technical SEO addresses the infrastructure Googlebot uses to read your website: server response headers, crawl budgets, render-blocking JavaScript, XML sitemaps, canonical tags, 301 loops, and Core Web Vitals performance.'
    },
    {
      q: 'How quickly can a website expect to see improvements after a technical overhaul?',
      a: 'Technical fixes often produce the fastest reactions in organic search. Once critical crawl blocks, noindex tags, or redirect chains are resolved, Google typically re-crawls and re-indexes pages within 7 to 21 days. As indexability and render speeds improve, ranking improvements compound over 60 to 90 days.'
    },
    {
      q: 'Do you work directly on our website code or provide audit recommendations?',
      a: 'Both. Depending on your team structure, I can either collaborate directly with your web developers by providing precise ticket specifications (with code snippets and XPath), or implement changes directly in your CMS, Git repository, or frontend framework.'
    },
    {
      q: 'Why is crawl budget important for large or e-commerce websites?',
      a: 'Googlebot allocates a finite amount of time and server requests to crawl your domain. On e-commerce sites with thousands of faceted filter URLs, internal search parameters, or pagination loops, bots waste their entire visit on useless pages while your high-margin commercial products remain unindexed.'
    },
    {
      q: 'How do you approach local SEO for businesses in Karachi?',
      a: 'Local search in Karachi requires district-level precision. I optimize your Google Business Profile, build verified NAP citations across Pakistani directories, inject LocalBusiness JSON-LD schema with exact geo-coordinates, and architect localized landing pages for key commercial hubs like DHA, Clifton, and Gulshan.'
    },
    {
      q: 'Can you fix Google Search Console indexing errors ("Crawled - currently not indexed")?',
      a: 'Yes. "Crawled - currently not indexed" usually indicates Googlebot accessed the page but deemed it low quality, duplicate, or lacking clear internal linking signals. I diagnose the content depth, canonical status, and internal link equity to ensure Google values and indexes the URL.'
    },
    {
      q: 'Do you require long-term binding monthly contracts?',
      a: 'No. Engagements can be structured either as a comprehensive one-time Technical & Architecture Audit (with clear implementation roadmap) or as a monthly architectural sprint where we iterate on crawling, intent clustering, and ranking expansion.'
    },
    {
      q: 'How do we start an SEO audit or collaboration?',
      a: 'Submit your website URL through the "Request SEO Audit" button. I will conduct an initial diagnostic pass of your domain and follow up with a clear breakdown of potential crawl issues, keyword opportunities, and recommended next steps.'
    }
  ];

  return (
    <section id="faq-section" className="py-24 sm:py-32 bg-[#060909] relative border-t border-white/5">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center max-w-2xl mx-auto mb-16">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-xs font-semibold text-[#00E59B] uppercase mb-4">
            <HelpCircle className="w-3.5 h-3.5" />
            <span>FREQUENTLY ASKED QUESTIONS</span>
          </div>

          <h2 className="text-3xl sm:text-5xl font-extrabold text-[#F4FAF7] tracking-tight leading-[1.12]">
            Straight Answers to{' '}
            <span className="text-gradient-emerald">Common Questions.</span>
          </h2>

          <p className="mt-4 text-base text-[#94A3B8]">
            Everything you need to know about technical audits, implementation, crawl optimization, and how we work together.
          </p>
        </div>

        {/* Minimalist Accordion */}
        <div className="space-y-3">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;

            return (
              <div
                key={idx}
                className={`rounded-2xl border transition-all duration-200 overflow-hidden ${
                  isOpen
                    ? 'bg-[#080D0D] border-emerald-500/30 shadow-[0_10px_30px_rgba(0,0,0,0.6)]'
                    : 'bg-[#080D0D]/60 border-white/6 hover:border-white/12'
                }`}
              >
                <button
                  onClick={() => setOpenIndex(isOpen ? null : idx)}
                  className="w-full p-5 sm:p-6 text-left flex items-center justify-between gap-4 focus:outline-none"
                  aria-expanded={isOpen}
                >
                  <span className="text-base sm:text-lg font-bold text-white">
                    {faq.q}
                  </span>
                  <div className={`w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 transition-transform duration-200 ${
                    isOpen ? 'bg-emerald-500/20 text-[#00E59B] rotate-180' : 'bg-white/5 text-[#5E736D]'
                  }`}>
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </button>

                {isOpen && (
                  <div className="px-5 sm:px-6 pb-6 pt-1 border-t border-white/5 text-sm text-[#94A3B8] leading-relaxed animate-in fade-in duration-200">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
};
